import { DashboardStats, MockOrder, ActivityLog } from './types';

export const MOCK_DASHBOARD_STATS: DashboardStats = {
  admin: {
    totalOrders: 28,
    pendingBilling: 5,
    pendingPacking: 3,
    readyForDelivery: 4,
    delivered: 14,
    recentActivityCount: 12,
  },
  callReceiver: {
    createdOrdersCount: 8,
    pendingOrdersCount: 3,
    scheduledOrdersCount: 2,
  },
  biller: {
    pendingBillingCount: 5,
    completedBillingCount: 12,
  },
  packer: {
    pendingPackingCount: 3,
    completedPackingCount: 15,
  },
  deliveryTeam: {
    readyForDeliveryCount: 4,
    assignedDeliveriesCount: 6,
    availableDriversCount: 3,
  },
  deliveryBoy: {
    assignedCount: 2,
    deliveredCount: 8,
    undeliveredCount: 1,
  },
};

export const MOCK_ORDERS: MockOrder[] = [
  {
    id: 'ORD-101',
    patientName: 'John Doe',
    doctorName: 'Dr. Sarah Smith',
    address: '123 Health Street, Flat 4B, Sector 5, Android City',
    contactNumber: '+1 555-0199',
    scheduledDateTime: '2026-08-14 10:00 AM',
    status: 'NEW',
    createdAt: '2026-08-13 02:30 PM',
    createdById: 'call_rec_1',
  },
  {
    id: 'ORD-102',
    patientName: 'Jane Johnson',
    doctorName: 'Dr. Robert Carter',
    address: '456 Wellness Boulevard, Android City',
    contactNumber: '+1 555-0188',
    scheduledDateTime: '2026-08-14 11:30 AM',
    status: 'BILLING_PENDING',
    createdAt: '2026-08-13 03:00 PM',
    createdById: 'call_rec_1',
  },
  {
    id: 'ORD-103',
    patientName: 'Michael Brown',
    doctorName: 'Dr. Alice Greenwood',
    address: '789 Care Lane, Android City',
    contactNumber: '+1 555-0177',
    scheduledDateTime: '2026-08-13 04:30 PM',
    status: 'BILLING_COMPLETED',
    createdAt: '2026-08-13 11:00 AM',
    createdById: 'call_rec_1',
    amount: 145.50,
  },
  {
    id: 'ORD-104',
    patientName: 'Emily Davis',
    doctorName: 'Dr. Sarah Smith',
    address: '101 Pharmacy Ave, Android City',
    contactNumber: '+1 555-0166',
    scheduledDateTime: '2026-08-13 05:00 PM',
    status: 'PACKING_PENDING',
    createdAt: '2026-08-13 09:15 AM',
    createdById: 'call_rec_1',
    amount: 89.99,
  },
  {
    id: 'ORD-105',
    patientName: 'David Wilson',
    doctorName: 'Dr. James Anderson',
    address: '222 Capsule Road, Android City',
    contactNumber: '+1 555-0155',
    scheduledDateTime: '2026-08-13 03:00 PM',
    status: 'PACKING_COMPLETED',
    createdAt: '2026-08-12 04:30 PM',
    createdById: 'call_rec_2',
    amount: 210.00,
  },
  {
    id: 'ORD-106',
    patientName: 'Robert Miller',
    doctorName: 'Dr. Sarah Smith',
    address: '333 Syringe Way, Android City',
    contactNumber: '+1 555-0144',
    scheduledDateTime: '2026-08-13 02:00 PM',
    status: 'READY_FOR_DELIVERY',
    createdAt: '2026-08-12 03:15 PM',
    createdById: 'call_rec_2',
    amount: 45.25,
  },
  {
    id: 'ORD-107',
    patientName: 'Patricia Taylor',
    doctorName: 'Dr. Robert Carter',
    address: '444 Bandage Street, Android City',
    contactNumber: '+1 555-0133',
    scheduledDateTime: '2026-08-13 01:00 PM',
    status: 'ASSIGNED',
    createdAt: '2026-08-12 02:00 PM',
    createdById: 'call_rec_2',
    amount: 120.50,
    assignedTo: 'Driver Jack',
  },
  {
    id: 'ORD-108',
    patientName: 'William Thomas',
    doctorName: 'Dr. James Anderson',
    address: '555 Remedy Road, Android City',
    contactNumber: '+1 555-0122',
    scheduledDateTime: '2026-08-13 12:00 PM',
    status: 'DELIVERED',
    createdAt: '2026-08-12 10:00 AM',
    createdById: 'call_rec_2',
    amount: 67.80,
    assignedTo: 'Driver Jack',
    remarks: 'Delivered to receptionist',
  },
  {
    id: 'ORD-109',
    patientName: 'Linda Jackson',
    doctorName: 'Dr. Alice Greenwood',
    address: '666 Healing Court, Android City',
    contactNumber: '+1 555-0111',
    scheduledDateTime: '2026-08-13 11:30 AM',
    status: 'UNDELIVERED',
    createdAt: '2026-08-12 09:00 AM',
    createdById: 'call_rec_1',
    amount: 35.00,
    assignedTo: 'Driver Jack',
    remarks: 'Customer not answering call, locked door',
  }
];

export const MOCK_ACTIVITY_LOGS: ActivityLog[] = [
  {
    id: 'LOG-001',
    user: 'receiver_user',
    role: 'CALL_RECEIVER',
    action: 'Created order',
    orderId: 'ORD-101',
    newStatus: 'NEW',
    timestamp: '2026-08-13 02:30 PM',
  },
  {
    id: 'LOG-002',
    user: 'receiver_user',
    role: 'CALL_RECEIVER',
    action: 'Created order',
    orderId: 'ORD-102',
    newStatus: 'NEW',
    timestamp: '2026-08-13 03:00 PM',
  },
  {
    id: 'LOG-003',
    user: 'biller_user',
    role: 'BILLER',
    action: 'Submitted invoice and uploaded bill image',
    orderId: 'ORD-103',
    previousStatus: 'BILLING_PENDING',
    newStatus: 'BILLING_COMPLETED',
    timestamp: '2026-08-13 03:15 PM',
  },
  {
    id: 'LOG-004',
    user: 'packer_user',
    role: 'PACKER',
    action: 'Packed and uploaded proof image',
    orderId: 'ORD-105',
    previousStatus: 'PACKING_PENDING',
    newStatus: 'PACKING_COMPLETED',
    timestamp: '2026-08-13 03:30 PM',
  },
  {
    id: 'LOG-005',
    user: 'dispatcher_user',
    role: 'DELIVERY_TEAM',
    action: 'Assigned order to Jack',
    orderId: 'ORD-107',
    previousStatus: 'READY_FOR_DELIVERY',
    newStatus: 'ASSIGNED',
    timestamp: '2026-08-13 03:45 PM',
  },
  {
    id: 'LOG-006',
    user: 'jack_rider',
    role: 'DELIVERY_BOY',
    action: 'Marked order as Delivered. Payment collected.',
    orderId: 'ORD-108',
    previousStatus: 'OUT_FOR_DELIVERY',
    newStatus: 'DELIVERED',
    timestamp: '2026-08-13 04:00 PM',
  }
];

export const MOCK_DELIVERY_BOYS = [
  { id: 'db_1', name: 'Driver Jack', phone: '+1 555-0101', status: 'Active' },
  { id: 'db_2', name: 'Driver Tom', phone: '+1 555-0102', status: 'Active' },
  { id: 'db_3', name: 'Driver Mark', phone: '+1 555-0103', status: 'Busy' },
];
